# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: df2369a39dd3060ec20522d07c9bb35ca9d8beafa84213a224ea96ea4f9fed8a424e9580e53c77aa359285bcb3685d6a677eba30358522d1ecd170b6ce1b01aa

test:
  secret_key_base: d90a07f589430ac6c8565ddf91ecea9e2b5c1963769a536c7073731128fe16ab1d9ca998d53ae61c443fc52f7643f66b44b996cd6be80d2d065da185c473e9a1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
